parameters:
  - name: pool
    displayName: 'Pool'
    type: string
    default: 'Self-hosted'
    values:
      - 'Azure Pipelines'
      - 'Self-hosted'

trigger:
  branches:
    include:
      - release/*
      - hotfix/*
  tags:
    include:
      - '*'

pr:
  branches:
    include:
      - master
      - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Gateway/paybyrd-deployment
      ref: refs/tags/7.11.0

variables:
  - template: 'variables.yml'

stages:
  - template: versioning/prepare.yml@templates
    parameters:
      pool: ${{ parameters.pool }}
  - template: library/csharp/linux/build.yml@templates
    parameters:
      pool: ${{ parameters.pool }}
      project_name: '${{variables.PROJECT_NAME}}'
      project_path: '${{variables.PROJECT_PATH}}'
      quality_gate:
        enabled: false
      ai_pull_request:
        enabled: false
  - template: nuget/linux/deploy.yml@templates
    parameters:
      artifact_name: ${{ variables.PROJECT_NAME }}
      pool: ${{ parameters.pool }}
      feed: 'external'
